CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

    CREATE TABLE USUARIOS (
    IDUSUARIO NUMBER DEFAULT SEQ_USUARIO.NEXTVAL PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROL VARCHAR2(20) NOT NULL
);

DROP TABLE USUARIOS;

DROP SEQUENCE SEQ_USUARIO;

SELECT * FROM USUARIOS;