-- Secuencias
CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SEQ_CATEGORIA;

DROP SEQUENCE SEQ_PRODUCTO;



-- Tabla CATEGORIA
CREATE TABLE CATEGORIA (
    IDCATEGORIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500)
);

-- Tabla PRODUCTO
CREATE TABLE PRODUCTO (
    IDPRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    PRECIO NUMBER(10,2) NOT NULL,
    IMAGEN VARCHAR2(255),
    DISPONIBLE NUMBER(1) DEFAULT 1,
    CATEGORIA_ID NUMBER,
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) 
        REFERENCES CATEGORIA(IDCATEGORIA)
);

-- Tabla PEDIDO
CREATE TABLE PEDIDO (
    IDPEDIDO NUMBER PRIMARY KEY,
    CLIENTE_ID NUMBER,
    FECHA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR2(20),
    DIRECCION_ENTREGA VARCHAR2(500),
    TOTAL NUMBER(10,2),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_ID) 
        REFERENCES CLIENTE(IDCLIENTE)
);

-- Tabla DETALLEPEDIDO
CREATE TABLE DETALLEPEDIDO (
    IDDETALLEPEDIDO NUMBER PRIMARY KEY,
    PEDIDO_ID NUMBER,
    PRODUCTO_ID NUMBER,
    CANTIDAD NUMBER(5),
    PRECIO_UNITARIO NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (PEDIDO_ID) 
        REFERENCES PEDIDO(IDPEDIDO),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(IDPRODUCTO)
);

-- Triggers para las secuencias
CREATE OR REPLACE TRIGGER TRG_CATEGORIA
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
  SELECT SEQ_CATEGORIA.NEXTVAL
  INTO :new.IDCATEGORIA
  FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTO
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
  SELECT SEQ_PRODUCTO.NEXTVAL
  INTO :new.IDPRODUCTO
  FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TRG_PEDIDO
BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
  SELECT SEQ_PEDIDO.NEXTVAL
  INTO :new.IDPEDIDO
  FROM dual;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETALLE_PEDIDO
BEFORE INSERT ON DETALLEPEDIDO
FOR EACH ROW
BEGIN
  SELECT SEQ_DETALLE_PEDIDO.NEXTVAL
  INTO :new.IDDETALLEPEDIDO
  FROM dual;
END;
/

-- Insertar categorías
INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, DESCRIPCION) 
VALUES (SEQ_CATEGORIA.NEXTVAL, 'Postres', 'Endulzate la Vida');

INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, DESCRIPCION) 
VALUES (SEQ_CATEGORIA.NEXTVAL, 'Bebidas', 'Tomate algo...');

-- Insertar productos
INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, IMAGEN, DISPONIBLE, CATEGORIA_ID)
VALUES (SEQ_PRODUCTO.NEXTVAL, 'Hot Cakes', 'Deliciosos hotcakes bañados de dulce', 40, '/assets/images/tequenos.jpg', 1, 2);

INSERT INTO PRODUCTO (IDPRODUCTO, NOMBRE, DESCRIPCION, PRECIO, IMAGEN, DISPONIBLE, CATEGORIA_ID)
VALUES (SEQ_PRODUCTO.NEXTVAL, 'Té de Menta', 'Calientito Té de Menta', 15, '/assets/images/lomo.jpg', 1, 4);


SELECT * FROM CATEGORIA;
SELECT * FROM PRODUCTO;

DELETE FROM PRODUCTO;
DELETE FROM CATEGORIA;